version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install awscli poetry
  build:
    commands:
      - poetry build
  post_build:
    commands:
      - aws codeartifact login --tool twine --domain $DOMAIN --domain-owner $DOMAIN_OWNER --repository $REPO
      - twine upload --repository codeartifact dist/*