version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install poetry
  build:
    commands:
      - poetry build
  post_build:
    commands:
      - aws codeartifact login --tool twine --domain example-domain --domain-owner 299557483172 --repository example_repository
      - twine upload --repository codeartifact dist/*